name: Wiki Scraper Workflow

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wiki-scraper
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

  test:
    - name: Run Tests
      uses: pytest

  deploy:
    - name: Run main flow
      run: python3 main.py
